variables:
  - &golang_image 'docker.io/golang:1.25'
  - &alpine_image 'owncloudci/alpine:latest'
  - &behat_image 'cs3org/behat:latest'
  - &ldap_image 'osixia/openldap:1.3.0'
  - &minio_image 'minio/mc:RELEASE.2021-10-07T04-19-58Z'
  - &woodpecker_wait_plugin_image 'ghcr.io/dvjn/woodpecker-is-it-up-yet-plugin'
  - &ceph_image 'ceph/daemon'
  - &nats_image 'nats:2.11-alpine'

when:
  - event:
      - push
      - manual
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - feature/*
  - event:
      - pull_request
      - cron

depends_on:
  - build

matrix:
  RUN_PART: [1, 2, 3, 4]

steps:
  - name: fetch-binary
    image: *minio_image
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_s3_access_key
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_s3_secret_key
      S3_BUCKET:
        from_secret: cache_s3_bucket
      S3_ENDPOINT: 'https://s3.ci.opencloud.eu'
    commands:
      - mc alias set s3 $S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
      - mc cp -a s3/$S3_BUCKET/${CI_REPO}/$CI_COMMIT_SHA-$CI_PIPELINE_NUMBER-revad $CI_WORKSPACE/cmd/revad/revad

  - name: wait-for-ldap
    image: *woodpecker_wait_plugin_image
    settings:
      host: ldap
      port: 389

  - name: wait-for-ceph
    image: *woodpecker_wait_plugin_image
    settings:
      host: ceph
      port: 8080

  - name: wait-for-nats
    image: *woodpecker_wait_plugin_image
    settings:
      host: nats
      port: 4222

  - name: revad-services
    image: *golang_image
    detach: true
    commands:
      - cd tests/oc-integration-tests/ci/
      - ../../../cmd/revad/revad -c frontend.toml &
      - ../../../cmd/revad/revad -c gateway.toml &
      - ../../../cmd/revad/revad -c shares.toml &
      - ../../../cmd/revad/revad -c storage-shares.toml &
      - ../../../cmd/revad/revad -c machine-auth.toml &
      - ../../../cmd/revad/revad -c storage-users-kvfs.toml &
      - ../../../cmd/revad/revad -c storage-publiclink.toml &
      - ../../../cmd/revad/revad -c permissions-demo-ci.toml &
      - ../../../cmd/revad/revad -c ldap-users.toml

  - name: wait-for-server
    image: *woodpecker_wait_plugin_image
    settings:
      host: revad-services
      port: 19000

  - name: clone-api-tests
    image: *alpine_image
    commands:
      - . ./.woodpecker.env
      - git clone -b $APITESTS_BRANCH --single-branch --no-tags $APITESTS_REPO_GIT_URL
      - cd opencloud
      - git checkout $APITESTS_COMMITID

  - name: opencloud-api-tests
    image: *behat_image
    environment:
      TEST_SERVER_URL: 'http://revad-services:20080'
      OC_REVA_DATA_ROOT: '/woodpecker/src/reva/data'
      DELETE_USER_DATA_CMD: 'rm -rf /woodpecker/src/reva/data/spaces/* /woodpecker/src/reva/data/blobs/* /woodpecker/src/reva/data/indexes/by-type/*'
      STORAGE_DRIVER: 'kvfs'
      TEST_WITH_LDAP: True
      REVA_LDAP_HOSTNAME: 'ldap'
      TEST_REVA: True
      SEND_SCENARIO_LINE_REFERENCES: True
      BEHAT_FILTER_TAGS: '~@skip&&~@skipOnReva&&~@env-config'
      DIVIDE_INTO_NUM_PARTS: '4'
      RUN_PART: '${RUN_PART}'
      EXPECTED_FAILURES_FILE: '/woodpecker/src/github.com/${CI_REPO}/tests/acceptance/expected-failures-on-KVFS-storage.md'
      ACCEPTANCE_TEST_TYPE: 'core-api'
    commands:
      - cd opencloud
      - make test-acceptance-api

  - name: requests-log
    image: *alpine_image
    when:
      - status: failure
    commands:
      - cd opencloud
      - cat tests/acceptance/logs/failed.log

services:
  ldap:
    image: *ldap_image
    environment:
      LDAP_DOMAIN: 'example.org'
      LDAP_ORGANISATION: 'example'
      LDAP_ADMIN_PASSWORD: 'admin'
      LDAP_TLS_VERIFY_CLIENT: 'never'
      LDAP_LOG_LEVEL: '0'
      HOSTNAME: 'ldap'

  ceph:
    image: *ceph_image
    environment:
      CEPH_DAEMON: 'demo'
      NETWORK_AUTO_DETECT: '4'
      MON_IP: '0.0.0.0'
      CEPH_PUBLIC_NETWORK: '0.0.0.0/0'
      RGW_CIVETWEB_PORT: '4000'
      RGW_NAME: 'ceph'
      CEPH_DEMO_UID: 'test-user'
      CEPH_DEMO_ACCESS_KEY: 'test'
      CEPH_DEMO_SECRET_KEY: 'test'
      CEPH_DEMO_BUCKET: 'test'

  nats:
    image: *nats_image
    commands:
      - nats-server -js
